### PR TITLE
Zhong wen fstm

### PR DESCRIPTION
**Pull request by M2ayill**
Add Chinese version

### CODE REVIEW

**Comment by cq674350529** [comment]
Wrong branch? Commits should be merged into `gitbook` branch?

**Comment by 0nise** [comment]
No, this is a new branch. When gitbook submits a new branch (version), it will open a new branch.

**Comment by 0nise** [comment]
> 错误的分支？提交应该合并到`gitbook`分支中吗？

No, this is a new branch. When gitbook submits a new branch (version), it will open a new branch.

**Comment by xxxxbxxxxx** [comment]
> Wrong branch? Commits should be merged into `gitbook` branch?

No, this is a new branch. When gitbook submits a new branch (version), it will open a new branch.

**Comment by scriptingxss** [comment]
Thank you for translating @M2ayill

**Comment by scriptingxss** [comment]
The PR was merged into master and has been reverted. I went ahead and created a new branch (https://github.com/scriptingxss/owasp-fstm/tree/zhong-wen-fstm) and will have GitBook sync to this branch as well. 

Can you send another PR @M2ayill ?

**Comment by scriptingxss** [comment]
GitBook URL ready to be synced 
https://scriptingxss.gitbook.io/firmware-security-testing-methodology/v/zhong-wen-fstm/

**Pull request merged**
